version: "3.8"

services:
  app-service:
    image: mattjsharp/app-service
    restart: "always"
    environment:
      AUTH_SERVICE_IP: ${AUTH_SERVICE_IP:-localhost} # Use service name for communication
    ports:
      - "8000:8000"
    depends_on:
      auth-service:
        condition: service_started
    networks:
      - app-network

  auth-service:
    image: mattjsharp/auth-service
    restart: "always"
    ports:
      - "3000:3000"
    networks:
      - app-network

  reverse-proxy:
    image: nginx:mainline-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx-conf:/etc/nginx/conf.d:ro
    depends_on:
      - app-service
    networks:
      - app-network

networks:
  app-network:
    driver: bridge